### ISSUE TITLE
data.registrationId is empty on Android

### ISSUE THREAD

**Issue by efstathiosntonas** [aggarwalankush/ionic2-push-base#3]
Hi, i'm using ionic 3, cordova 6.5.0, cordova android 6.1.2, phonegap-push-plugin 1.10.2
`ionic run android`

 pushObject.on('registration').subscribe((data: any) => {
      console.log("device token ->", data.registrationId);
      //TODO - send device token to server
    });

returns emtpy, if i alert(data.registrationId) the alert shows the device id.

Any idea why this is happening?

**Comment by dlecan** [comment]
See #4, just `console.log("device token -> " + data.registrationId);` (note `+` concatenation)

**Comment by efstathiosntonas** [comment]
Intresting bug but if i console log the data.registrationId only, it returns empty again.

I ve checked on console if app has permission to display notifications and it has. 

Cant figure out what is going on...

**Comment by dlecan** [comment]
If `alert` works, your final test:
```javascript
pushObject.on('registration').subscribe((data: any) => {
  let regId = data.registrationId;
  alert(regId);
  console.log("device token -> " + regId); // should work too
});
```

**Comment by efstathiosntonas** [comment]
@dlecan suddenly it works... Thanks for your help! I don't know what was going wrong...
